package org.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import static org.junit.Assert.assertThat;

public class TestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test() {
    driver.get("http://localhost:9898/BlackAndWhite/test001.html?_ijt=cetvkaii48gedr78bmnp347cl2&_ij_reload=RELOAD_ON_CHANGE");
    driver.manage().window().setSize(new Dimension(1106, 806));
    driver.findElement(By.id("date")).click();
    driver.findElement(By.id("date")).sendKeys("0002-01-01");
    driver.findElement(By.id("date")).sendKeys("0020-01-01");
    driver.findElement(By.id("date")).sendKeys("0200-01-01");
    driver.findElement(By.id("date")).sendKeys("2000-01-01");
    driver.findElement(By.id("date")).click();
    driver.findElement(By.id("date")).sendKeys("2000-12-01");
    driver.findElement(By.id("date")).sendKeys("2000-12-02");
    driver.findElement(By.id("date")).sendKeys("2000-12-20");
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    assertThat(driver.switchTo().alert().getText(), is("星期三"));
  }
}
